version: '3.8'

services:
  grafana:

    image: grafana/grafana:11.0.0

    container_name: grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana
 
    environment:
 
      - GF_SECURITY_ADMIN_PASSWORD=sua_senha_super_forte_aqui
    restart: unless-stopped

volumes:
  grafana-data: {}