version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: wordpress_db

    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root_super_forte
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: sua_senha_wordpress_super_forte
    restart: unless-stopped

  wordpress:

    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_site

    ports:
      - "8080:80"

    volumes:
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: sua_senha_wordpress_super_forte
      WORDPRESS_DB_NAME: wordpress
    restart: unless-stopped

volumes:
  db_data: {}
  wordpress_files: {}